name: Test

on:
  push:
    branches:
    - master
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Setup poetry
      id: poetry_setup
      uses: ItsDrike/setup-poetry@v1
      with:
          python-version: ${{ matrix.python-version }}
          install-args: --with github_hooks --sync

    - name: Run checks
      run: poetry run make test
